at-center-server/src/main/java/ru/iteco/at/center/model/entity/User.java
package ru.iteco.at.center.model.entity;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import ru.iteco.at.center.api.annotation.SearchStringFieldMarker;
import ru.iteco.at.center.exception.EmptyEntityException;
import ru.iteco.at.center.model.dto.UserDTO;
import ru.iteco.at.center.enumerate.Role;
import ru.iteco.at.center.exception.EmptyRoleSetException;

import javax.persistence.*;
import java.io.Serializable;
import java.util.*;

@Setter
@Getter
@Entity
@Table(name = "app_user")
@EqualsAndHashCode(of = "id", callSuper = true)
public class User extends AbstractEntity implements UserDetails, Serializable {

    @Nullable
    @Column(unique = true)
    @SearchStringFieldMarker(prettyName = "Login")
    private String login;

    @Nullable
    private String password;

    @Nullable
    private String token;

    @Column(nullable=false, columnDefinition = "BOOLEAN DEFAULT FALSE")
    private boolean locked = false;

    @NotNull
    @ElementCollection(targetClass = Role.class, fetch = FetchType.EAGER)
    @CollectionTable(name = "app_user_role", joinColumns = @JoinColumn(name = "user_id"))
    @Enumerated(EnumType.STRING)
    private Set<Role> roles = new HashSet<>();

    @Nullable
    @SearchStringFieldMarker(prettyName = "Email")
    private String email;

    @NotNull
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user", orphanRemoval = true)
    private List<JobInstance> jobInstance = new ArrayList<>();

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        List<SimpleGrantedAuthority> authorityList = new java.util.ArrayList<>();
        getRoles().forEach(role -> authorityList.add(new SimpleGrantedAuthority(role.name())));
        return authorityList;
    }

    @Nullable
    @Override
    public String getPassword() {
        return password;
    }

    @Nullable
    @Override
    public String getUsername() {
        return login;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return !locked;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }

    @Nullable
    @Column(name = "lastName")
    @SearchStringFieldMarker(prettyName = "Last name")
    private String lastName;

    @Nullable
    @Column(name = "firstName")
    @SearchStringFieldMarker(prettyName = "First name")
    private String firstName;

    @Nullable
    @Column(name = "middleName")
    @SearchStringFieldMarker(prettyName = "Middle name")
    private String middleName;

    @NotNull
    public static Set<Role> getRoleSet(@NotNull final Set<String> userDTORoles) {
        if (userDTORoles == null || userDTORoles.isEmpty()) throw new EmptyRoleSetException();
        @NotNull Set<Role> roles = new HashSet<>();
        for (@NotNull final String currentRole : userDTORoles) {
            switch (currentRole) {
                case ("ADMIN"):
                    roles.add(Role.ADMIN);
                    break;
                case ("USER"):
                    roles.add(Role.USER);
                    break;
                case ("GUEST"):
                    roles.add(Role.GUEST);
                    break;
            }
        }
        return roles;
    }

    @NotNull
    public static User toUser(@Nullable final UserDTO userDTO) {
        if (userDTO == null) throw new EmptyEntityException();
        @NotNull User user = new User();
        user.setId(userDTO.getId());
        user.setLogin(userDTO.getLogin());
        user.setPassword(userDTO.getPassword());
        user.setEmail(userDTO.getEmail());
        user.setFirstName(userDTO.getFirstName());
        user.setMiddleName(userDTO.getMiddleName());
        user.setLastName(userDTO.getLastName());
        user.setToken(userDTO.getToken());
        user.setRoles(getRoleSet(userDTO.getRoles()));
        return user;
    }

}

at-center-server/src/main/webapp/WEB-INF/views/management/settings.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:j="http://xmlns.jcp.org/jsf/core">

<h:body>
    <ui:composition template="../../templates/main-template.xhtml">
        <ui:define name="title">Settings - AT Center</ui:define>

        <ui:define name="content">
            <h1>SETTINGS</h1>
            <h:form>
                <p:panel id="panel" header="SETTINGS" styleClass="label-input-table">

                    <!-- Раскомментировать для отображения сообщений в верхней части формы -->
                    <!--                    <p:messages id="msgs"/>-->

                    <h:panelGrid columns="3" cellpadding="5">



                    </h:panelGrid>
                </p:panel>
                <p:commandButton ajax="false"
                                 type="submit" value="SAVE"
                                 action="#{adminBean.saveSettings}"/>
                <p:commandButton ajax="false" immediate="true"
                                 type="submit" value="CANCEL"
                                 action="pretty:index"/>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

at-center-server/src/main/webapp/WEB-INF/views/management/user-add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
<h:body>
    <ui:composition template="../../templates/main-template.xhtml">
        <ui:define name="title">Sign up - AT Center</ui:define>

        <ui:define name="content">
            <p:panel id="signup-pnl" header="CREATE NEW USER" styleClass="label-input-table">
                <h:form prependId="false">
                    <p:messages id="msgs"/>
                    <h:panelGrid columns="3" cellpadding="5">
                        <p:outputLabel for="login" value="LOGIN"/>
                        <p:inputText id="login" value="#{userBean.registryUser.login}" styleClass="full-width"
                                     validator="#{userBean.validateRegistrationLogin}" required="true">
                            <f:validateLength minimum="2"/>
                            <p:ajax update="msgLogin" event="keyup"/>
                        </p:inputText>
                        <p:message for="login" id="msgLogin" display="1"/>

                        <p:outputLabel for="lastName" value="LAST NAME"/>
                        <p:inputText id="lastName" value="#{userBean.registryUser.lastName}" required="true"
                                     validatorMessage="Please enter last name.">
                            <f:validateRegex pattern="[^\s\d][^\d]*"/>
                            <p:ajax update="msgLastname" event="keyup"/>
                        </p:inputText>
                        <p:message for="lastName" id="msgLastname"/>

                        <p:outputLabel for="firstName" value="FIRST NAME"/>
                        <p:inputText id="firstName" value="#{userBean.registryUser.firstName}" required="true"
                                     validatorMessage="Please enter first name.">
                            <f:validateRegex pattern="[^\s\d][^\d]+"/>
                            <p:ajax update="msgFirstname" event="keyup"/>
                        </p:inputText>
                        <p:message for="firstName" id="msgFirstname"/>

                        <p:outputLabel for="middleName" value="MIDDLE NAME"/>
                        <p:inputText id="middleName" value="#{userBean.registryUser.middleName}"/>
                        <br/>

                        <p:outputLabel for="email" value="E-MAIL"/>
                        <p:inputText id="email" value="#{userBean.registryUser.email}" required="true"
                                     validatorMessage="Invalid email format">
                            <f:validateRegex
                                    pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$"/>
                            <p:ajax update="msgEmail" event="keyup"/>
                        </p:inputText>
                        <p:message for="email" id="msgEmail"/>

                        <p:outputLabel for="password" value="PASSWORD"/>
                        <p:password id="password" value="#{userBean.registryUser.password}" match="password-2"
                                    required="true">
                            <f:validateRegex pattern=".{3,8}"/>
                            <p:ajax update="msgPassword" event="keyup"/>
                        </p:password>
                        <p:message for="password" id="msgPassword"/>

                        <p:outputLabel for="password-2" value="CONFIRM PASSWORD"/>
                        <p:password id="password-2" value="#{userBean.registryUser.password}" required="true">
                            <f:validateRegex pattern=".{3,8}"/>
                            <p:ajax update="msgPassword-2" event="keyup"/>
                        </p:password>
                        <p:message for="password" id="msgPassword-2"/>

                        <h:form>
                            <p:commandButton ajax="false" action="#{userBean.createUser()}" value="SAVE"/>
                            <p:commandButton ajax="false" type="submit" value="CANCEL" immediate="true"
                                             actionListener="#{userBean.resetRegistryUser}"
                                             action="pretty:userManagement"/>
                        </h:form>
                    </h:panelGrid>
                </h:form>
            </p:panel>
        </ui:define>
    </ui:composition>
</h:body>
</html>

at-center-server/src/main/webapp/WEB-INF/views/management/user-edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:j="http://xmlns.jcp.org/jsf/core">

<h:body>
    <ui:composition template="../../templates/main-template.xhtml">
        <ui:define name="title">User edit - AT Center</ui:define>

        <ui:define name="content">
            <j:metadata>
                <j:viewAction action="#{adminBean.viewEditUser()}"/>
            </j:metadata>
            <h1>EDIT USER</h1>
            <h:form>
                <p:panel id="panel" header="GENERAL INFORMATION" styleClass="label-input-table">

                    <!-- Раскомментировать для отображения сообщений в верхней части формы -->
                    <!--                    <p:messages id="msgs"/>-->

                    <h:panelGrid columns="3" cellpadding="5">
                        <p:outputLabel for="login" value="LOGIN"/>
                        <p:inputText id="login" value="#{adminBean.userEdit.login}" styleClass="full-width"
                                     validator="#{adminBean.validateUserEditLogin}" required="true">
                            <f:validateLength minimum="2"/>
                            <p:ajax update="msgLogin" event="keyup"/>
                        </p:inputText>
                        <p:message for="login" id="msgLogin"/>

                        <p:outputLabel for="email" value="EMAIL"/>
                        <p:inputText id="email" value="#{adminBean.userEdit.email}" styleClass="full-width"
                                     validatorMessage="Invalid email format.">
                            <f:validateRegex
                                    pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$"/>
                            <p:ajax update="msgEmail" event="keyup"/>
                        </p:inputText>
                        <p:message for="email" id="msgEmail"/>

                        <p:outputLabel for="lastName" value="LAST NAME"/>
                        <p:inputText id="lastName" styleClass="full-width" value="#{adminBean.userEdit.lastName}"
                                     validatorMessage="Please enter last name.">
                            <f:validateRegex pattern="[^\s\d]{1,}"/>
                            <p:ajax update="msgLastName" event="keyup"/>
                        </p:inputText>
                        <p:message for="lastName" id="msgLastName"/>

                        <p:outputLabel for="firstName" value="FIRST NAME"/>
                        <p:inputText id="firstName" styleClass="full-width" value="#{adminBean.userEdit.firstName}"
                                     validatorMessage="Please enter first name.">
                            <f:validateRegex pattern="[^\s\d]{2,}"/>
                            <p:ajax update="msgFirstName" event="keyup"/>
                        </p:inputText>
                        <p:message for="firstName" id="msgFirstName"/>

                        <p:outputLabel for="middleName" value="MIDDLE NAME"/>
                        <p:inputText id="middleName" styleClass="full-width" value="#{adminBean.userEdit.middleName}"
                                     validatorMessage="Please use the alphabet.">
                            <f:validateRegex pattern="[^\s\d]{2,}"/>
                            <p:ajax update="msgMiddleName" event="keyup"/>
                        </p:inputText>
                        <p:message for="middleName" id="msgMiddleName"/>

                        <p:outputLabel for="roles" value="ROLES"/>
                        <p:selectManyCheckbox id="roles"
                                              value="#{adminBean.selectedRoles}">
                            <f:selectItems value="#{adminBean.roles}"
                                           var="role"
                                           itemLabel="#{role}"
                                           itemValue="#{role}"/>
                        </p:selectManyCheckbox>
                        <p:message for="roles" id="msgRoles"/>

                        <p:outputLabel for="lock" value="LOCK"/>
                        <p:selectBooleanCheckbox id="lock" value="#{adminBean.userEdit.locked}" itemLabel="LOCK"/>
                    </h:panelGrid>
                </p:panel>
                <p:commandButton ajax="false"
                                 type="submit" value="SAVE"
                                 action="#{adminBean.saveUserEdit(adminBean.userEdit)}"/>
                <p:commandButton ajax="false" immediate="true"
                                 type="submit" value="CANCEL"
                                 action="pretty:userManagement"/>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

at-center-server/src/main/webapp/WEB-INF/views/management/user-management.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

<f:metadata>
    <f:viewAction action="#{adminBean.setList(searchBean.resetSearch())}" />
</f:metadata>

<h:head>
</h:head>
<h:body>
    <ui:composition template="../../templates/main-template.xhtml">
        <ui:define name="title">User Management - AT Center</ui:define>

        <ui:define name="content">

            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes"/>
                <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no"/>
            </p:confirmDialog>

            <h:form>
                <h1>USER MANAGEMENT</h1>
                <p:panel id="panel" header="SEARCH USER">
                    <table class="table-search" cellspacing="0" cellpadding="0" border="0">
                        <tr>
                            <td width="350" nowrap="nowrap" class="ui-fluid">
                                <p:selectCheckboxMenu value="#{searchBean.selectedFields}"
                                                      label="CHOOSE FIELDS FOR SEARCH" filter="true" required="true"
                                                      requiredMessage="Choose fields for search"
                                                      filterMatchMode="startsWith"
                                                      multiple="true">
                                    <f:selectItems value="#{searchBean.userFieldPrettyName}"/>
                                </p:selectCheckboxMenu>
                            </td>
                            <td nowrap="nowrap" width="20">&#xA0;</td>
                            <td class="ui-fluid">
                                <p:inputText placeholder="ENTER SEARCH STRING"
                                             value="#{searchBean.searchString}"
                                             required="false" requiredMessage="Enter search string"/>
                            </td>
                            <td nowrap="nowrap" align="right">
                                <p:commandButton styleClass="buttons" value="FIND" ajax="false"
                                                 action="#{adminBean.setList(searchBean.searchUserByString())}"
                                                 update="users"/>
                                <p:commandButton styleClass="buttons" value="RESET" ajax="false"
                                                 immediate="true"
                                                 action="#{adminBean.setList(searchBean.resetSearch())}"
                                                 update="users">
                                    <p:resetInput target="panel" />
                                </p:commandButton>
                            </td>
                        </tr>
                    </table>
                </p:panel>
            </h:form>

            <h:form>
                <p:dataTable var="user" value="#{adminBean.list}" rows="10" paginator="true" id="users"
                             paginationPosition="bottom" paginatorAlwaysVisible="false"
                             paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks}
                             {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="10,50,100" rowIndexVar="rowIndex" widgetVar="jobsTable"
                             sortBy="#{user.login}">
                    <f:facet name="header">
                        <p:outputPanel>
                            <h:outputText style="text-align: left; font-size: 1.2em" value="USER LIST"/>
                        </p:outputPanel>
                    </f:facet>

                    <p:column headerText="№" style="padding: 0; text-align: center; width:50px">
                        <h:outputText value="#{rowIndex + 1}"/>
                    </p:column>

                    <p:column headerText="LOGIN"
                              style="text-align: left; width:250px"
                              sortBy="#{user.login}">
                        <h:outputText value="#{user.login}"/>
                    </p:column>

                    <p:column headerText="E-MAIL"
                              style="text-align: left"
                              sortBy="#{user.email}">
                        <h:outputText value="#{user.email}"/>
                    </p:column>

                    <p:column headerText="FIRST NAME"
                              style="text-align: left"
                              sortBy="#{user.firstName}">
                        <h:outputText value="#{user.firstName}"/>
                    </p:column>

                    <p:column headerText="MIDDLE NAME"
                              style="text-align: left"
                              sortBy="#{user.middleName}">
                        <h:outputText value="#{user.middleName}"/>
                    </p:column>

                    <p:column headerText="LAST NAME"
                              style="text-align: left"
                              sortBy="#{user.lastName}">
                        <h:outputText value="#{user.lastName}"/>
                    </p:column>

                    <p:column headerText="ROLES" style="text-align: left; width:150px">
                        <ui:repeat value="#{user.authorities}" var="role">
                            <h:outputText value="#{role.authority} "/>
                        </ui:repeat>
                    </p:column>

                    <p:column style="padding: 0; text-align: center; width:50px">
                        <p:commandLink style="color: #333333; font-size: 1.5em" ajax="false"
                                       action="#{adminBean.viewProfileUser(user)}" class="pi pi-eye"/>
                    </p:column>

                    <p:column style="padding: 0; text-align: center; width:50px">
                        <p:commandLink style="color: #333333; font-size: 1.5em" title="Edit" ajax="false"
                                       action="#{adminBean.editUser(user)}" class="pi pi-pencil"/>
                    </p:column>
                    <p:column style="padding: 0; text-align: center; width:50px">
                        <p:commandLink style="color: #333333; font-size: 1.5em" title="Delete"
                                       action="#{adminBean.deleteUser(user)}" update="users" class="pi pi-trash">
                            <p:confirm header="Delete user" message="Delete user with login: #{user.login}?"
                                       icon="pi pi-exclamation-triangle"/>
                        </p:commandLink>
                    </p:column>
                </p:dataTable>
            </h:form>

            <h:form>
                <p:commandButton ajax="false" type="submit" value="CREATE" action="pretty:addUser"/>
            </h:form>

        </ui:define>
    </ui:composition>
</h:body>
</html>

at-center-server/src/main/webapp/WEB-INF/views/management/user-profile.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<f:metadata>
    <f:viewAction action="#{adminBean.viewEditUser()}" />
</f:metadata>
<h:body>
    <ui:composition template="../../templates/main-template.xhtml">
        <ui:define name="title"> Profile - AT Center</ui:define>

        <ui:define name="content">
            <h1>VIEW PROFILE</h1>
            <p:panel id="profile-pnl" header="PROFILE" styleClass="table-info">
                <h:form prependId="false">
                    <p:messages id="msgs"/>
                    <h:panelGrid columns="3" cellpadding="5" layout="center">
                        <p:outputLabel value="LOGIN"/>
                        <p:outputLabel id="login" value="#{adminBean.userEdit.login}"/>

                        <p:message for="login" id="msgLogin"/>

                        <p:outputLabel value="LAST NAME"/>
                        <p:outputLabel id="lastName" styleClass="full-width" value="#{adminBean.userEdit.lastName}"/>

                        <p:message for="lastName" id="msgLastname"/>

                        <p:outputLabel value="FIRST NAME"/>
                        <p:outputLabel id="firstName" styleClass="full-width" value="#{adminBean.userEdit.firstName}"/>

                        <p:message for="firstName" id="msgFirstname"/>

                        <p:outputLabel for="middleName" value="MIDDLE NAME"/>
                        <p:outputLabel id="middleName" styleClass="full-width" value="#{adminBean.userEdit.middleName}"/>
                        <br/>

                        <p:outputLabel value="E-MAIL"/>
                        <p:outputLabel id="email" styleClass="full-width" value="#{adminBean.userEdit.email}"/>
                        <p:message for="email" id="msgEmail"/>
                    </h:panelGrid>
                </h:form>
            </p:panel>

            <p:commandButton action="pretty:userManagement" styleClass="buttons" value="BACK"/>

        </ui:define>
    </ui:composition>
</h:body>
</html>