at-center-server/src/main/java/ru/iteco/at/center/model/entity/Job.java
package ru.iteco.at.center.model.entity;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import ru.iteco.at.center.exception.EmptyEntityException;
import ru.iteco.at.center.model.dto.JobDTO;
import ru.iteco.at.center.model.dto.UserDTO;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "app_job")
@NoArgsConstructor
@EqualsAndHashCode(of = "id", callSuper = true)
public class Job extends AbstractEntity implements Serializable {

    @Nullable
    private String name;

    @NotNull
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "job", cascade = {CascadeType.PERSIST, CascadeType.REMOVE}, orphanRemoval = true)
    private List<JobInstance> jobInstanceList = new ArrayList<>();

    @NotNull
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "job", cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE}, orphanRemoval = true)
    private List<CategoryJob> categoryJobList = new ArrayList<>();

    @Nullable
    private String buildNumber;

    @Nullable
    private String description;

}

at-center-server/src/main/java/ru/iteco/at/center/model/entity/JobInstance.java
package ru.iteco.at.center.model.entity;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.springframework.format.annotation.DateTimeFormat;
import ru.iteco.at.center.enumerate.StatusJob;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Getter
@Setter
@Entity
@NoArgsConstructor
@Table(name = "app_jobinstance")
@EqualsAndHashCode(of = "id", callSuper = true)
public class JobInstance extends AbstractEntity implements Serializable {

    @Nullable
    @ManyToOne
    @JoinColumn(name = "job_id")
    private Job job;

    @Nullable
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    @Nullable
    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name = "system_id")
    private OperationSystem operationSystem;

    @NotNull
    @OneToMany(fetch = FetchType.LAZY,
            mappedBy = "jobInstance",
            orphanRemoval = true,
            cascade = {CascadeType.PERSIST})
    private List<Metrik> metrikList = new ArrayList<>();

    @Nullable
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    private Date dateBegin;

    @Nullable
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    private Date dateEnd;

    @Nullable
    @Enumerated(EnumType.STRING)
    private StatusJob statusJob;

    @Nullable
    private String memoryOfJob;
}

at-center-server/src/main/java/ru/iteco/at/center/api/rest/JobController.java
package ru.iteco.at.center.api.rest;

import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import ru.iteco.at.center.model.dto.JobDTO;

@RestController
@RequestMapping("/job")
public interface JobController {

    @PostMapping(consumes = "application/json")
    void post(@RequestBody JobDTO jobDTO);

    @RequestMapping(value = "/deleteJob")
    @PostMapping(consumes = "application/json")
    void deleteJob(@RequestBody JobDTO jobDTO);
}

at-center-server/src/main/java/ru/iteco/at/center/faces/JobInstanceManagedBean.java
package ru.iteco.at.center.faces;

import lombok.Getter;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.primefaces.model.charts.line.LineChartModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;
import ru.iteco.at.center.api.service.MetrikService;
import ru.iteco.at.center.api.service.MetrikValueService;
import ru.iteco.at.center.enumerate.TypeMetrik;
import ru.iteco.at.center.model.entity.JobInstance;
import ru.iteco.at.center.model.entity.Metrik;
import ru.iteco.at.center.model.entity.MetrikValue;
import ru.iteco.at.center.service.JobInstanceServiceImpl;
import ru.iteco.at.center.util.GraphsBuilderUtil;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import java.util.*;

@Getter
@Setter
@SessionScoped
@ManagedBean(name = "jobInstanceBean")
public class JobInstanceManagedBean extends SpringBeanAutowiringSupport {

    private static final String FORMAT_STRING = "Graph dependency between %s and %s metrics";

    @Autowired
    private JobInstanceServiceImpl jobInstanceService;

    @Autowired
    private MetrikService metrikService;

    @Autowired
    private MetrikValueService metrikValueService;

    @NotNull
    private JobInstance jobInstance = new JobInstance();

    private String fromPage;

    private String selectedOption;

    private int numberPointsOnGraphic = 1; // 1 - all points

    private String baseNumberPoints = "All";

    private String baseLeftBound = "Min";

    private String baseRightBound = "Max";

    private int leftBoundMsOnGraphic = 0;

    private long rightBoundMsOnGraphic = 9_999_999_999_999L;

    private static Map<String, String> numberPointsMap;

    private static Map<String, String> numberMsBoundsMap;

    private String localeCode = "en"; //default value

    static {
        numberPointsMap = new LinkedHashMap<String, String>();
        numberPointsMap.put("All", "1");
        numberPointsMap.put("100", "100");
        numberPointsMap.put("50", "50");
        numberPointsMap.put("20", "20");
        numberPointsMap.put("10", "10");
    }

    static {
        numberMsBoundsMap = new LinkedHashMap<>();
        numberMsBoundsMap.put("Max        ms.", "10000000");
        numberMsBoundsMap.put("1.500.000  ms.", "1500000");
        numberMsBoundsMap.put("1.200.000  ms.", "1200000");
        numberMsBoundsMap.put("1.000.000  ms.", "1000000");
        numberMsBoundsMap.put("800.000    ms.", "800000");
        numberMsBoundsMap.put("500.000    ms.", "500000");
        numberMsBoundsMap.put("300.000    ms.", "300000");
        numberMsBoundsMap.put("200.000    ms.", "200000");
        numberMsBoundsMap.put("100.000    ms.", "100000");
        numberMsBoundsMap.put("70.000     ms.", "70000");
        numberMsBoundsMap.put("50.000     ms.", "50000");
        numberMsBoundsMap.put("40.000     ms.", "40000");
        numberMsBoundsMap.put("30.000     ms.", "30000");
        numberMsBoundsMap.put("20.000     ms.", "20000");
        numberMsBoundsMap.put("10.000     ms.", "10000");
        numberMsBoundsMap.put("5.000      ms.", "5000");
        numberMsBoundsMap.put("1.000      ms.", "1000");
        numberMsBoundsMap.put("Min        ms.", "0");
    }

    public void changePointsOnGraphic(ValueChangeEvent e) {
        numberPointsOnGraphic = Integer.parseInt(e.getNewValue().toString());
        System.err.println("point1");
    }

    public void changePointsLeftValueOfRangeOnGraphic(ValueChangeEvent e) {
        leftBoundMsOnGraphic = Integer.parseInt(e.getNewValue().toString());
    }

    public void changePointsRightValueOfRangeOnGraphic(ValueChangeEvent e) {
        rightBoundMsOnGraphic = Integer.parseInt(e.getNewValue().toString());
    }

    public Map<String, String> getNumberPointsMap() {
        return numberPointsMap;
    }

    public int getLeftBoundMsOnGraphic() {
        return leftBoundMsOnGraphic;
    }

    public void setLeftBoundMsOnGraphic(int leftBoundMsOnGraphic) {
        this.leftBoundMsOnGraphic = leftBoundMsOnGraphic;
    }

    public long getRightBoundMsOnGraphic() {
        return rightBoundMsOnGraphic;
    }

    public void setRightBoundMsOnGraphic(int rightBoundMsOnGraphic) {
        this.rightBoundMsOnGraphic = rightBoundMsOnGraphic;
    }

    public String getBaseRightBound() {
        return baseRightBound;
    }

    public void setBaseRightBound(String baseRightBound) {
        this.baseRightBound = baseRightBound;
    }

    public Map<String, String> getNumberMsBoundsMap() {
        return numberMsBoundsMap;
    }

    public static void setNumberMsBoundsMap(Map<String, String> numberMsBoundsMap) {
        JobInstanceManagedBean.numberMsBoundsMap = numberMsBoundsMap;
    }

    @NotNull
    public String viewJobInstance(@NotNull final JobInstance jobInstance) {
        this.jobInstance = jobInstance;
        return "pretty:viewJobInstance";
    }

    public boolean metricExists() {
        return metrikService.existsByJobInstanceId(jobInstance.getId());
    }

    @NotNull
    public Iterable<Metrik> metricList() {
        return metrikService.findAllByJobInstanceId(jobInstance.getId());
    }

    public String deleteJobInstance(final JobInstance jobInstance) {
        jobInstanceService.delete(jobInstance);
        return "pretty:jobList";
    }

    private String getAxesLabel(@NotNull final Metrik metric) {
        @NotNull String result = "";
        if (metric.getType() != null) {
            result = metric.getName() + ", " + metric.getType().getMeasure();
        }
        return result;
    }

    private void updateAsAverage(
            @NotNull final List<MetrikValue> listMetricValueY,
            @NotNull final List<MetrikValue> listMetricValueX,
            @NotNull final List<Number> listObjectY
    ) {
        for (int i = 0; i < listMetricValueY.size(); i++) {
            @Nullable final String valueY = listMetricValueY.get(i).getValue();
            @Nullable final String valueX = listMetricValueX.get(i).getValue();

            if (valueY != null && valueX != null) {
                final long longValueY = Long.parseLong(valueY);
                final long longValueX = Long.parseLong(valueX);
                @NotNull final Double averageValue = (longValueX == 0) ? longValueY : longValueY * 1.0 / longValueX;
                listObjectY.add(i, averageValue);
            }
        }
    }

    @NotNull
    public LineChartModel getGraphLineModel(
            final TypeMetrik typeMetricY,
            final boolean isAverage,
            final TypeMetrik typeMetricX
    ) {
        @NotNull final List<Number> listObjectY = new ArrayList<>();
        @NotNull final List<Object> listObjectX = new ArrayList<>();
        @NotNull final Metrik yMetric = metrikService.findByJobInstanceIdAndType(jobInstance.getId(), typeMetricY);
        @NotNull final Metrik xMetric = metrikService.findByJobInstanceIdAndType(jobInstance.getId(), typeMetricX);

        @NotNull final List<MetrikValue> propertyListMetricValueX =
                metrikValueService.findAllByMetrikIdOrderByTimeStamp(xMetric.getId());

        @NotNull final List<MetrikValue> propertyListMetricValueY =
                metrikValueService.findAllByMetrikIdOrderByTimeStamp(yMetric.getId());

        @NotNull final List<MetrikValue> listMetricValueY = new ArrayList<>();

        @NotNull final List<MetrikValue> listMetricValueX = new ArrayList<>();

        int counter = -1;

        for (MetrikValue metrikValue : propertyListMetricValueX) {
            counter++;
            int metricValue = Integer.parseInt(metrikValue.getValue());
            if (metricValue < rightBoundMsOnGraphic && metricValue > leftBoundMsOnGraphic) {
                listMetricValueX.add(metrikValue);
                listMetricValueY.add(propertyListMetricValueY.get(counter));
            }
        }

        @NotNull String yAxesLabel = getAxesLabel(yMetric);
        @NotNull String xAxesLabel = getAxesLabel(xMetric);
        @NotNull final String graphLabel = String.format(FORMAT_STRING, yMetric.getName(), xMetric.getName());

        if (isAverage) {
            updateAsAverage(listMetricValueY, listMetricValueX, listObjectY);
            yAxesLabel = "Average number of objects per ms, amount";
        } else {
            listMetricValueY.forEach(metricValue -> {
                if (metricValue.getValue() != null) {
                    @NotNull final Long value = Long.parseLong(metricValue.getValue());
                    listObjectY.add(value);
                }
            });
        }

        listMetricValueX.forEach(metricValue -> {
            if (metricValue.getValue() != null) {
                listObjectX.add(metricValue.getValue());
            }
        });

        @NotNull final List<Number> listObjectLessY = new ArrayList<>();
        @NotNull final List<Object> listObjectLessX = new ArrayList<>();

        int period;
        if (numberPointsOnGraphic == 1) {
            period = 1;
        } else {
            period = listObjectY.size() / numberPointsOnGraphic;
        }

        int j = 0;
        for (int i = 0; i < listObjectY.size(); i++) {
            j++;
            if (j > period) {
                listObjectLessY.add(listObjectY.get(i));
                if (i + 1 < listMetricValueX.size()) listObjectLessX.add(listObjectX.get(i));
                j = 0;
            }
        }

        @NotNull final LineChartModel graphLineModel = GraphsBuilderUtil.buildLineGraphModel(
                listObjectLessY, listObjectLessX, yAxesLabel, xAxesLabel, graphLabel);
        return graphLineModel;
    }

    @NotNull
    public LineChartModel getModelForObjectAmountLoadRAMGraph() {
        return getGraphLineModel(TypeMetrik.CURRENT_AMOUNT, false, TypeMetrik.LOAD_AVERAGE);
    }

    @NotNull

at-center-server/src/main/webapp/WEB-INF/views/job/job-edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:body>
    <ui:composition template="../../templates/main-template.xhtml">
        <ui:define name="title">Job edit - AT Center</ui:define>

        <ui:define name="content">
            <f:metadata>
                <f:viewAction action="#{jobBean.viewEditJob()}"/>
            </f:metadata>
            <h1>EDIT JOB</h1>
            <p:panel id="panel" header="GENERAL INFORMATION" styleClass="label-input-table">
                <h:form>
                    <h:panelGrid columns="2" cellpadding="5">
                        <p:outputLabel for="name" value="NAME"/>
                        <br/>
                        <p:inputText id="name" value="#{jobBean.job.name}">
                            <p:ajax update="msgName" event="keyup"/>
                        </p:inputText>
                        <p:message for="name" id="msgName"/>
                        <p:outputLabel for="description" value="DESCRIPTION"/>
                        <br/>
                        <p:inputText id="description" value="#{jobBean.job.description}">
                            <p:ajax update="msgDescription" event="keyup"/>
                        </p:inputText>
                        <p:message for="description" id="msgDescription"/>
                    </h:panelGrid>
                </h:form>
            </p:panel>
            <h:form>
                <p:commandButton ajax="false" type="submit" value="SAVE" action="#{jobBean.saveJob()}"/>
                <p:commandButton ajax="false" type="submit" value="CANCEL" action="pretty:jobList"/>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

at-center-server/src/main/webapp/WEB-INF/views/job/job-instance-profile-view.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<f:metadata>
    <f:viewAction action="#{jobInstanceBean.viewJobInstanceProfile}"/>
</f:metadata>

<h:body>
    <ui:composition template="../../templates/main-template.xhtml">
        <ui:define name="title">JobInstance profile - AT Center</ui:define>

        <ui:define name="content">
            <h:form>
                <p:panel id="panel" header="JOB INSTANCE PROFILE" styleClass="table-info">
                    <h:panelGrid columns="2" cellpadding="5">

                        <p:outputLabel for="jobName" value="JOB NAME"/>
                        <h:outputText id="jobName" value="#{jobInstanceBean.jobInstance.job.name}"/>

                        <p:outputLabel for="jobBuildNumber" value="BUILD NUMBER"/>
                        <h:outputText id="jobBuildNumber" value="#{jobInstanceBean.jobInstance.job.buildNumber}"/>

                        <p:outputLabel for="userLogin" value="USER LOGIN"/>
                        <h:outputText id="userLogin" value="#{jobInstanceBean.jobInstance.user.login}"/>

                        <p:outputLabel for="operationSystem" value="OPERATION SYSTEM"/>
                        <h:outputText id="operationSystem"
                                      value="#{jobInstanceBean.jobInstance.operationSystem.name} #{jobInstanceBean.jobInstance.operationSystem.systemCapacity.label}"/>

                        <p:outputLabel for="jobInstanceStatus" value="JOB INSTANCE STATUS"/>
                        <h:outputText id="jobInstanceStatus" value="#{jobInstanceBean.jobInstance.statusJob}"/>

                        <p:outputLabel for="dateBegin" value="START"/>
                        <h:outputText id="dateBegin" value="#{jobInstanceBean.jobInstance.dateBegin}"/>

                        <p:outputLabel for="dateEnd" value="FINISH"/>
                        <h:outputText id="dateEnd" value="#{jobInstanceBean.jobInstance.dateEnd}"/>

                    </h:panelGrid>
                </p:panel>
                <p:commandButton ajax="false" value="BACK" action="#{jobInstanceBean.returnPreviousPage()}"/>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

at-center-server/src/main/webapp/WEB-INF/views/job/job-instance-view.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:tr="http://java.sun.com/jsp/jstl/core">

<h:body>
    <ui:composition template="../../templates/main-template.xhtml">
        <ui:define name="title">Job list - AT Center</ui:define>

        <ui:define name="content">
            <h1>VIEW JOB INSTANCE</h1>
            <style>
                .tbl1 {
                    width: 100%;
                    border-collapse: collapse;
                }

                .col1, .col2, .col3 {
                    padding: 1%;
                }

                .col1 {
                    width: 15%;
                }

                .col2 {
                    width: 35%;
                }

                .col3 {
                    width: 45%;
                }
            </style>
            <p:panel id="job-instance-pnl" header="GENERAL INFO" style="margin-bottom: 1%; font-size: 1.2em">
                <table class="tbl1">
                    <tr>
                        <td class="col1">
                            <h:outputLabel value="JOB NAME:"/>
                        </td>
                        <td class="col2">
                            <h:outputText id="jobName" styleClass="full-width"
                                          value="#{jobInstanceBean.jobInstance.job.name}"/>
                        </td>
                    </tr>
                    <tr>
                        <td class="col1">
                            <h:outputLabel value="JOB INSTANCE ID:"/>
                        </td>
                        <td class="col2">
                            <h:outputText id="jobInstanceId" styleClass="full-width"
                                          value="#{jobInstanceBean.jobInstance.id}"/>
                        </td>
                        <td class="col1">
                        </td>
                        <td class="col2">
                        </td>
                    </tr>
                    <tr>
                        <td class="col1">
                            <h:outputLabel value="SYSTEM:"/>
                        </td>
                        <td class="col2">
                            <h:outputText id="systemName" styleClass="full-width"
                                          value="#{jobInstanceBean.jobInstance.operationSystem.name}"/>
                            <h:outputText id="space" styleClass="full-width" value=" "/>
                            <h:outputText id="systemCapacity" styleClass="full-width"
                                          value="#{jobInstanceBean.jobInstance.operationSystem.systemCapacity.label} "/>
                        </td>
                        <td class="col1">
                        </td>
                        <td class="col2">
                        </td>
                    </tr>
                    <tr>
                        <td class="col1">
                            <h:outputLabel value="DATE BEGIN:"/>
                        </td>
                        <td class="col2">
                            <h:outputText id="dateBegin" styleClass="full-width"
                                          value="#{dateUtil.getDateAndTimeFromDate(jobInstanceBean.jobInstance.dateBegin)}">
                            </h:outputText>
                        </td>
                        <td class="col1">
                        </td>
                        <td class="col2">
                        </td>
                    </tr>
                    <tr>
                        <td class="col1">
                            <h:outputLabel value="DATE END:"/>
                        </td>
                        <td class="col2">
                            <h:outputText id="dateEnd" styleClass="full-width"
                                          value="#{dateUtil.getDateAndTimeFromDate(jobInstanceBean.jobInstance.dateEnd)}">
                            </h:outputText>
                        </td>
                        <td class="col1">
                        </td>
                        <td class="col2">
                        </td>
                    </tr>
                </table>
            </p:panel>

            <p:panel id="metrik-pnl"
                     style="margin-bottom: 1%; font-size: 1.2em"
                     header="GRAPHICS OF JOB INSTANCE"
                     rendered="#{jobInstanceBean.metricExists()}">
                <table class="tbl1">
                    <tr>
                        <td class="col3">
                            <p:lineChart model="#{jobInstanceBean.modelForObjectAmountTimeSpentGraph}"/>
                        </td>
                        <td class="col3">
                            <p:lineChart model="#{jobInstanceBean.modelForAverageObjectValueTimeSpent}"/>
                        </td>
                    </tr>
                    <tr>
                        <td class="col3">
                            <p:lineChart model="#{jobInstanceBean.modelForObjectAmountLoadRAMGraph}"/>
                        </td>
                        <td class="col3">
                            <p:lineChart model="#{jobInstanceBean.modelForLoadRAMTimeSpentGraph}"/>
                        </td>
                    </tr>
                </table>
            </p:panel>

            <p:panel id="graphics-settings-pnl"
                     style="margin-bottom: 1%; font-size: 1.2em"
                     header="GRAPHICS SETTINGS">
                <h:form>
                    <h:panelGrid columns="2" cellpadding="7">
                        <p:outputLabel for="@next" value="NUMBER POINTS ON GRAPHICS:"/>
                        <p:selectOneMenu value="#{jobInstanceBean.baseNumberPoints}"
                                         valueChangeListener="#{jobInstanceBean.changePointsOnGraphic}">
                            <f:selectItems value="#{jobInstanceBean.numberPointsMap}" />
                            <p:ajax update="@this, metrik-pnl"/>
                        </p:selectOneMenu>
                    </h:panelGrid>
                </h:form>
                <h:form>
                    <h:panelGrid columns="2" cellpadding="7">
                        <p:outputLabel for="@next" value="LEFT BOUND OF DIAPASON TIME:"/>
                        <p:selectOneMenu value="#{jobInstanceBean.baseLeftBound}"
                                         valueChangeListener="#{jobInstanceBean.changePointsLeftValueOfRangeOnGraphic}">
                            <f:selectItems value="#{jobInstanceBean.numberMsBoundsMap}" />
                            <p:ajax update="@this, metrik-pnl"/>
                        </p:selectOneMenu>
                    </h:panelGrid>
                </h:form>
                <h:form>
                    <h:panelGrid columns="2" cellpadding="7">
                        <p:outputLabel for="@next" value="RIGHT BOUND OF DIAPASON TIME:"/>
                        <p:selectOneMenu value="#{jobInstanceBean.baseRightBound}"
                                         valueChangeListener="#{jobInstanceBean.changePointsRightValueOfRangeOnGraphic}">
                            <f:selectItems value="#{jobInstanceBean.numberMsBoundsMap}" />
                            <p:ajax update="@this, metrik-pnl"/>
                        </p:selectOneMenu>
                    </h:panelGrid>
                </h:form>
            </p:panel>

            <h:form id="form">
                <p:dataTable var="metrik" value="#{metrikBean.list(jobInstanceBean.jobInstance.id)}" rows="12"
                             paginator="true" id="metriks" paginationPosition="bottom"
                             paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="6,12,16" rowIndexVar="rowIndex">
                    <f:facet name="header">
                        <p:outputPanel>
                            <h:outputText style="text-align: left; font-size: 1.2em" value="METRIK LIST"/>
                        </p:outputPanel>
                    </f:facet>

                    <p:column headerText="№" style="padding: 0; text-align: center; width:50px">
                        <h:outputText value="#{rowIndex + 1}"/>
                    </p:column>
                    <p:column headerText="NAME" style="width:300px; text-align: left">
                        <h:outputText value="#{metrik.name}"/>
                    </p:column>
                    <p:column headerText="TYPE" style="text-align: left">
                        <h:outputText value="#{metrik.type.label}"/>
                    </p:column>

                    <p:column style="padding: 0; text-align: center; width:50px">
                        <p:commandLink style="color: #333333; font-size: 1.5em" ajax="false"
                                       action="#{metrikBean.viewMetric(metrik)}" class="pi pi-eye"/>
                    </p:column>
                    <p:column style="padding: 0; text-align: center; width:50px"
                              rendered="#{userBean.hasRole('ADMIN')}">
                        <p:commandLink style="color: #333333; font-size: 1.5em"
                                       action="#{metrikBean.deleteMetric(metrik)}" update="metriks" class="pi pi-trash">
                            <p:confirm header="Delete metrik" message="Delete metrik with name: #{metrik.name}?"
                                       icon="pi pi-exclamation-triangle"/>
                        </p:commandLink>
                    </p:column>
                </p:dataTable>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

at-center-server/src/main/webapp/WEB-INF/views/job/job-profile-view.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<f:metadata>
    <f:viewAction action="#{jobBean.viewEditJob()}" />
</f:metadata>
<h:body>
    <ui:composition template="../../templates/main-template.xhtml">
        <ui:define name="title">Job profile - AT Center</ui:define>

        <ui:define name="content">
            <h1>VIEW JOB INFO</h1>
            <p:panel id="panel" header="JOB PROFILE" styleClass="table-info">
                <h:form>
                    <h:panelGrid columns="2" cellpadding="5">

                        <p:outputLabel value="NAME"/>
                        <p:outputLabel value="#{jobBean.job.name}"/>

                        <p:outputLabel value="BUILD NUMBER"/>
                        <p:outputLabel value="#{jobBean.job.buildNumber}"/>

                        <p:outputLabel value="DESCRIPTION"/>
                        <p:outputLabel value="#{jobBean.job.description}"/>

                    </h:panelGrid>
                </h:form>
            </p:panel>
            <p:commandButton action="pretty:jobList" styleClass="buttons" value="BACK"/>
        </ui:define>
    </ui:composition>
</h:body>
</html>